import { type FC, useState } from 'react';

interface CategoryFilterProps {
    categories: any[];
    selectedCategories: any[];
    onChangeCategory: (slug: string) => void;
}

export const CategoryFilter: FC<CategoryFilterProps> = ({
    categories,
    selectedCategories,
    onChangeCategory,
}) => {
    return (
        <div className="flex flex-col gap-4">
            <p className="p">Categories</p>

            <div className="flex flex-col gap-2.5">
                {categories.map((cat: any, index: number) => {
                    return (
                        <label
                            key={index}
                            className="label flex gap-2 whitespace-nowrap text-ellipsis"
                        >
                            {/* ClassName was generated by claude */}
                            <input
                                className="appearance-none w-[18px] h-[18px] bg-white border border-primary rounded-sm
                            grid place-content-center cursor-pointer
                            before:content-[''] before:w-[10px] before:h-[10px] before:scale-0
                            before:bg-primary before:transition-transform
                            before:[clip-path:polygon(14%_44%,0_65%,50%_100%,100%_16%,80%_0,43%_62%)]
                            checked:before:scale-100"
                                type="checkbox"
                                checked={Boolean(
                                    selectedCategories.find(
                                        (filterCat) => cat.slug === filterCat
                                    )
                                )}
                                onChange={() => onChangeCategory(cat.slug)}
                            />
                            {cat.name}
                        </label>
                    );
                })}
            </div>

            <hr />
        </div>
    );
};
